[package]
name = "starkli"
version = "0.0.0"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "Starkli (/ˈstɑːrklaɪ/), a blazing fast CLI tool for Starknet powered by starknet-rs"

[dependencies]
anyhow = "1.0.71"
cairo-lang-starknet = { git = "https://github.com/starkware-libs/cairo", rev = "v1.1.0" }
chrono = "0.4.24"
clap = { version = "4.2.7", features = ["derive", "env"] }
clap_complete = "4.2.2"
colored = "2.0.0"
colored_json = "3.1.0"
regex = "1.8.1"
rpassword = "7.2.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
serde_with = "2.3.2"
shellexpand = "3.1.0"
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }
tokio = { version = "1.28.1", default-features = false, features = ["macros", "rt-multi-thread"] }
url = "2.3.1"
