[package]
name = "starkli"
version = "0.0.0"
authors = ["Jonathan LEI <me@xjonathan.dev>"]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "Starkli (/ˈstɑːrklaɪ/), a blazing fast CLI tool for Starknet powered by starknet-rs"

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
cairo-lang-starknet = "=1.1.0"
chrono = "0.4.26"
clap = { version = "4.3.3", features = ["derive", "env"] }
clap_complete = "4.3.1"
colored = "2.0.0"
colored_json = "3.2.0"
regex = "1.8.4"
rpassword = "7.2.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
shellexpand = "3.1.0"
serde_with = "2.3.3"
starknet = "0.3.0"
thiserror = "1.0.40"
tokio = { version = "1.28.2", default-features = false, features = ["macros", "rt-multi-thread"] }
url = "2.4.0"
